// Generated by IcedCoffeeScript 1.7.1-b
(function() {
  exports.transform = function(x, options) {
    return x.icedTransform(options);
  };

  exports.runtime = require('iced-runtime');

}).call(this);
